---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/duckdb --version
      register: duckdb_test_output
    - name: duckdb --version
      debug:
        msg: '{{ duckdb_test_output.stdout }}'
