---
- include_role:
    name: andrewrothstein.unarchivedeps
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: check for install at {{ duckdb_install_exe }}
  become: true
  stat:
    path: '{{ duckdb_install_exe }}'
  changed_when: false
  register: duckdb_binary
- when: not duckdb_binary.stat.exists
  block:
    - name: downloading {{ duckdb_url }} to {{ duckdb_tmp_archive }}
      become: true
      become_user: root
      get_url:
        url: '{{ duckdb_url }}'
        dest: '{{ duckdb_tmp_archive }}'
        checksum: '{{ duckdb_checksum }}'
        mode: 0644
    - name: mkdir {{ duckdb_install_dir }}
      become: true
      become_user: root
      file:
        path: '{{ duckdb_install_dir }}'
        mode: 0755
        state: directory
    - name: unarchiving {{ duckdb_tmp_archive }}
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ duckdb_tmp_archive }}'
        dest: '{{ duckdb_install_dir }}'
        creates: '{{ duckdb_install_exe }}'
  always:
    - name: rm {{ duckdb_tmp_archive }}
      become: true
      become_user: root
      file:
        path: '{{ duckdb_tmp_archive }}'
        state: absent
- name: linking {{ duckdb_link }} to {{ duckdb_install_exe }}
  become: true
  become_user: root
  file:
    dest: '{{ duckdb_link }}'
    src: '{{ duckdb_install_exe }}'
    state: link
