---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Check for install at {{ duckdb_install_exe }}
  become: true
  ansible.builtin.stat:
    path: '{{ duckdb_install_exe }}'
  changed_when: false
  register: duckdb_binary
- name: Downloading and installing
  when: not duckdb_binary.stat.exists
  block:
    - name: Downloading {{ duckdb_url }} to {{ duckdb_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ duckdb_url }}'
        dest: '{{ duckdb_tmp_archive }}'
        checksum: '{{ duckdb_checksum }}'
        mode: '644'
    - name: Mkdir {{ duckdb_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ duckdb_install_dir }}'
        mode: '755'
        state: directory
    - name: Unarchiving {{ duckdb_tmp_archive }}
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ duckdb_tmp_archive }}'
        dest: '{{ duckdb_install_dir }}'
        creates: '{{ duckdb_install_exe }}'
  always:
    - name: Rm {{ duckdb_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ duckdb_tmp_archive }}'
        state: absent
- name: Linking {{ duckdb_link }} to {{ duckdb_install_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    dest: '{{ duckdb_link }}'
    src: '{{ duckdb_install_exe }}'
    state: link
